name: 'Setup Neovim'
description: 'Sets up Neovim in your GitHub Actions workflow.'
author: 'David Bloss'
inputs:
  neovim_version:
    description: 'Neovim release version'
    default: 'stable'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
