name: Tests

on:
  push:
    branches: [main]
  pull_request:
    paths:
      - '.github/workflows/test.yml'
      - 'src/*'

jobs:
  setup-neovim-stable:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Up Neovim - Stable
        uses: ./
      - name: Print Neovim version
        run: |
          nvim --version

  setup-neovim-nightly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Up Neovim - Nightly
        uses: ./
        with:
          neovim-version: nightly
      - name: Print Neovim version
        run: |
          nvim --version
