name: Tests

on:
  push:
    branches: [main]
  pull_request:
    paths:
      - '.github/workflows/test.yml'
      - 'src/*'

jobs:
  setup-neovim-stable:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Up Neovim - Stable
        uses: ./
      - name: Print Neovim version
        run: |
          echo "Setup Neovim with stable version..."
          nvim --version

  setup-neovim-linux64-old:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Up Neovim - v0.10.3
        uses: ./
        with:
          neovim-version: v0.10.3
      - name: Verify Neovim version
        run: |
          echo "Setup Neovim with version..."
          nvim --version
          nvim --version | grep v0.10.3 || exit 1
          echo "Expected Neovim version installed"

  setup-neovim-nightly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Up Neovim - Nightly
        uses: ./
        with:
          neovim-version: nightly
      - name: Print Neovim version
        run: |
          echo "Setup Neovim with nightly version..."
          nvim --version
